# Accent and UI colors
accent = "#b59790"
active_border_color = "#d6d3de"
active_tab_background = "#a5a0b6"

# Cursor colors
cursor = "#e2dddc"

# Primary colors
foreground = "#FAFCFB"
background = "#0c0b0c"

# Selection colors
selection_foreground = "#0c0b0c"
selection_background = "#FAFCFB"

bg = "#0c0b0c"
lighter_bg = "#0c0b0c"
selection = "#FAFCFB"
muted = "#584e51"
dark_fg = "#584e51"
fg = "#FAFCFB"
light_fg = "#cfd3cd"
bright_fg = "#e2dddc"

red = "#c38b7b"
yellow = "#6B5E73"
green = "#87a9b0"
cyan = "#a5a0b6"
blue = "#b59790"
purple = "#c4d8e2"
bright_red = "#c38b7b"
bright_yellow = "#6B5E73"
bright_green = "#87a9b0"
bright_cyan = "#a5a0b6"
bright_blue = "#b59790"
bright_purple = "#c4d8e2"
